# fly.toml app configuration file generated for 8i-api-winter-fog-4570 on 2024-01-12T15:00:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "8i-api-winter-fog-4570"
primary_region = "bog"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  [[services.ports]]
    handlers = ["http"]
    port = "8080"
    check = "http://0.0.0.0:8080/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
