app = "8i-test-machine"
primary_region = "bog"

[experimental]
  cmd = ["/bin/app"]

[build]
  dockerfile = "Dockerfile"

[env]
  API_URL="8i-test-machine.fly.dev"
  API_TOKENS_EXPIRATION_TIME = "86400"
  HOST = "0.0.0.0"
  MONGO_DB_NAME = "test"
  PORT = "8080"
  PRO_PRODUCT_ID="160756"
  PRO_MONTHLY_VARIANT_ID="202405"
  PRO_ANNUALLY_VARIANT_ID="202400"
  ENABLE_EMAIL_VERIFICATION="true"
  BREVO_CUSTOMERS_LIST_ID="7"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = ""
  internal_port = 0

  [[services.ports]]
    port = 8080
    handlers = ["http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
